
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::ActivitiesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
RSpec.describe 'ActivitiesApi' do
  before do
    # run before each test
    @instance = ConnectWise::ActivitiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActivitiesApi' do
    it 'should create an instance of ActivitiesApi' do
      expect(@instance).to be_instance_of(ConnectWise::ActivitiesApi)
    end
  end

  # unit tests for sales_activities_count_get
  #
  # Get Activities Count
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :custom_field_conditions
  # @return [Count]
  describe 'sales_activities_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_get
  #
  # Get Activities
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :order_by
  # @option opts [String] :childconditions
  # @option opts [String] :customfieldconditions
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @return [Array<Activity>]
  describe 'sales_activities_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_id_delete
  #
  # Delete Activity By Id
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'sales_activities_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_id_get
  #
  # Get Activity By Id
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [Activity]
  describe 'sales_activities_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_id_patch
  #
  # Update Activity
  # @param id
  # @param operations
  # @param [Hash] opts the optional parameters
  # @return [Activity]
  describe 'sales_activities_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_id_put
  #
  # Replace Activity
  # @param id
  # @param activity
  # @param [Hash] opts the optional parameters
  # @return [Activity]
  describe 'sales_activities_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_post
  #
  # Create Activity
  # @param activity
  # @param [Hash] opts the optional parameters
  # @return [Activity]
  describe 'sales_activities_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
