
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::ActivityTypesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
RSpec.describe 'ActivityTypesApi' do
  before do
    # run before each test
    @instance = ConnectWise::ActivityTypesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActivityTypesApi' do
    it 'should create an instance of ActivityTypesApi' do
      expect(@instance).to be_instance_of(ConnectWise::ActivityTypesApi)
    end
  end

  # unit tests for sales_activities_types_count_get
  #
  # Get Activity Types Count
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @return [Count]
  describe 'sales_activities_types_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_types_get
  #
  # Get Activity Types
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :order_by
  # @option opts [String] :childconditions
  # @option opts [String] :customfieldconditions
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @return [Array<ActivityType>]
  describe 'sales_activities_types_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_types_id_delete
  #
  # Delete Activity Type By Id
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'sales_activities_types_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_types_id_get
  #
  # Get Activity Type By Id
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [ActivityType]
  describe 'sales_activities_types_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_types_id_patch
  #
  # Update Activity Type
  # @param id
  # @param operations
  # @param [Hash] opts the optional parameters
  # @return [ActivityType]
  describe 'sales_activities_types_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_types_id_put
  #
  # Replace Activity Type
  # @param id
  # @param activity_type
  # @param [Hash] opts the optional parameters
  # @return [ActivityType]
  describe 'sales_activities_types_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_activities_types_post
  #
  # Create Activity Type
  # @param activity_type
  # @param [Hash] opts the optional parameters
  # @return [ActivityType]
  describe 'sales_activities_types_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
