
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::BatchApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BatchApi' do
  before do
    # run before each test
    @instance = ConnectWise::BatchApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BatchApi' do
    it 'should create an instance of BatchApi' do
      expect(@instance).to be_instance_of(ConnectWise::BatchApi)
    end
  end

  # unit tests for system_batch_post
  # 
  # Process Batch Requests
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [BatchResponse]
  describe 'system_batch_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
