
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::BoardTypesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
RSpec.describe 'BoardTypesApi' do
  before do
    # run before each test
    @instance = ConnectWise::BoardTypesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BoardTypesApi' do
    it 'should create an instance of BoardTypesApi' do
      expect(@instance).to be_instance_of(ConnectWise::BoardTypesApi)
    end
  end

  # unit tests for service_boards_id_types_count_get
  #
  # Get Types Count
  # @param id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @return [Count]
  describe 'service_boards_id_types_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for service_boards_id_types_get
  #
  # Get Types
  # @param id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :order_by
  # @option opts [String] :childconditions
  # @option opts [String] :customfieldconditions
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @return [Array<BoardType>]
  describe 'service_boards_id_types_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for service_boards_id_types_post
  #
  # Create Type
  # @param id
  # @param board_type
  # @param [Hash] opts the optional parameters
  # @return [BoardType]
  describe 'service_boards_id_types_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for service_boards_id_types_type_id_delete
  #
  # Delete Type By Id
  # @param id
  # @param type_id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'service_boards_id_types_type_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for service_boards_id_types_type_id_get
  #
  # Get Type By Id
  # @param id
  # @param type_id
  # @param [Hash] opts the optional parameters
  # @return [BoardType]
  describe 'service_boards_id_types_type_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for service_boards_id_types_type_id_patch
  #
  # Update Types
  # @param id
  # @param type_id
  # @param operations
  # @param [Hash] opts the optional parameters
  # @return [BoardType]
  describe 'service_boards_id_types_type_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for service_boards_id_types_type_id_put
  #
  # Replace Types
  # @param id
  # @param type_id
  # @param board_type
  # @param [Hash] opts the optional parameters
  # @return [BoardType]
  describe 'service_boards_id_types_type_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
