=begin
#ConnectWise API

#ConnectWise API

OpenAPI spec version: 1.0.0
Contact: platform@connectwise.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::CampaignEmailsOpenedApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CampaignEmailsOpenedApi' do
  before do
    # run before each test
    @instance = ConnectWise::CampaignEmailsOpenedApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CampaignEmailsOpenedApi' do
    it 'should create an instact of CampaignEmailsOpenedApi' do
      expect(@instance).to be_instance_of(ConnectWise::CampaignEmailsOpenedApi)
    end
  end

  # unit tests for marketing_campaigns_id_emails_opened_count_get
  # 
  # Get Emails Opened Count
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @return [Count]
  describe 'marketing_campaigns_id_emails_opened_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for marketing_campaigns_id_emails_opened_email_opened_id_delete
  # 
  # Delete Email Opened By Id
  # @param id 
  # @param email_opened_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'marketing_campaigns_id_emails_opened_email_opened_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for marketing_campaigns_id_emails_opened_email_opened_id_get
  # 
  # Get Email Opened By Id
  # @param id 
  # @param email_opened_id 
  # @param [Hash] opts the optional parameters
  # @return [EmailOpened]
  describe 'marketing_campaigns_id_emails_opened_email_opened_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for marketing_campaigns_id_emails_opened_email_opened_id_patch
  # 
  # Update Email Opened
  # @param id 
  # @param email_opened_id 
  # @param operations 
  # @param [Hash] opts the optional parameters
  # @return [EmailOpened]
  describe 'marketing_campaigns_id_emails_opened_email_opened_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for marketing_campaigns_id_emails_opened_email_opened_id_put
  # 
  # Replace Email Opened
  # @param id 
  # @param email_opened_id 
  # @param email_opened 
  # @param [Hash] opts the optional parameters
  # @return [EmailOpened]
  describe 'marketing_campaigns_id_emails_opened_email_opened_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for marketing_campaigns_id_emails_opened_get
  # 
  # Get Emails Opened
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @option opts [String] :order_by 
  # @option opts [String] :childconditions 
  # @option opts [String] :customfieldconditions 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @return [Array<EmailOpened>]
  describe 'marketing_campaigns_id_emails_opened_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for marketing_campaigns_id_emails_opened_post
  # 
  # Create Email Opened
  # @param id 
  # @param email_opened 
  # @param [Hash] opts the optional parameters
  # @return [EmailOpened]
  describe 'marketing_campaigns_id_emails_opened_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
