
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::ContactRelationshipsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContactRelationshipsApi' do
  before do
    # run before each test
    @instance = ConnectWise::ContactRelationshipsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactRelationshipsApi' do
    it 'should create an instance of ContactRelationshipsApi' do
      expect(@instance).to be_instance_of(ConnectWise::ContactRelationshipsApi)
    end
  end

  # unit tests for company_contacts_relationships_count_get
  # 
  # Get Contact Relationships Count
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @return [Count]
  describe 'company_contacts_relationships_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for company_contacts_relationships_get
  # 
  # Get Contact Relationships
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @option opts [String] :order_by 
  # @option opts [String] :childconditions 
  # @option opts [String] :customfieldconditions 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @return [Array<ContactRelationship>]
  describe 'company_contacts_relationships_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for company_contacts_relationships_id_delete
  # 
  # Delete Contact Relationship By Id
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'company_contacts_relationships_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for company_contacts_relationships_id_get
  # 
  # Get Contact Relationship By Id
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ContactRelationship]
  describe 'company_contacts_relationships_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for company_contacts_relationships_id_patch
  # 
  # Update Contact Relationship
  # @param id 
  # @param operations 
  # @param [Hash] opts the optional parameters
  # @return [ContactRelationship]
  describe 'company_contacts_relationships_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for company_contacts_relationships_id_put
  # 
  # Replace Contact Relationship
  # @param id 
  # @param contact_relationship 
  # @param [Hash] opts the optional parameters
  # @return [ContactRelationship]
  describe 'company_contacts_relationships_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for company_contacts_relationships_post
  # 
  # Create Contact Relationship
  # @param contact_relationship 
  # @param [Hash] opts the optional parameters
  # @return [ContactRelationship]
  describe 'company_contacts_relationships_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
