
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::CrmsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CrmsApi' do
  before do
    # run before each test
    @instance = ConnectWise::CrmsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CrmsApi' do
    it 'should create an instance of CrmsApi' do
      expect(@instance).to be_instance_of(ConnectWise::CrmsApi)
    end
  end

  # unit tests for system_my_company_crm_count_get
  # 
  # Get Crms Count
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @return [Count]
  describe 'system_my_company_crm_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_my_company_crm_get
  # 
  # Get Crms
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @option opts [String] :order_by 
  # @option opts [String] :childconditions 
  # @option opts [String] :customfieldconditions 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @return [Array<Crm>]
  describe 'system_my_company_crm_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_my_company_crm_id_get
  # 
  # Get Crm By Id
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Crm]
  describe 'system_my_company_crm_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_my_company_crm_id_patch
  # 
  # Update Crm
  # @param id 
  # @param operations 
  # @param [Hash] opts the optional parameters
  # @return [Crm]
  describe 'system_my_company_crm_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_my_company_crm_id_put
  # 
  # Replace Crm
  # @param id 
  # @param crm 
  # @param [Hash] opts the optional parameters
  # @return [Crm]
  describe 'system_my_company_crm_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
