
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::CurrenciesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
RSpec.describe 'CurrenciesApi' do
  before do
    # run before each test
    @instance = ConnectWise::CurrenciesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CurrenciesApi' do
    it 'should create an instance of CurrenciesApi' do
      expect(@instance).to be_instance_of(ConnectWise::CurrenciesApi)
    end
  end

  # unit tests for finance_currencies_count_get
  #
  # Get Currencies Count
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @return [Count]
  describe 'finance_currencies_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finance_currencies_get
  #
  # Get Currencies
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :order_by
  # @option opts [String] :childconditions
  # @option opts [String] :customfieldconditions
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @return [Array<Currency>]
  describe 'finance_currencies_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finance_currencies_id_delete
  #
  # Delete Currency By Id
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'finance_currencies_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finance_currencies_id_get
  #
  # Get Currency By Id
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [Currency]
  describe 'finance_currencies_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finance_currencies_id_patch
  #
  # Update Currency
  # @param id
  # @param operations
  # @param [Hash] opts the optional parameters
  # @return [Currency]
  describe 'finance_currencies_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finance_currencies_id_put
  #
  # Replace Currency
  # @param id
  # @param currency
  # @param [Hash] opts the optional parameters
  # @return [Currency]
  describe 'finance_currencies_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finance_currencies_post
  #
  # Create Currency
  # @param currency
  # @param [Hash] opts the optional parameters
  # @return [Currency]
  describe 'finance_currencies_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
