=begin
#ConnectWise API

#ConnectWise API

OpenAPI spec version: 1.0.0
Contact: platform@connectwise.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::InvoicePaymentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InvoicePaymentsApi' do
  before do
    # run before each test
    @instance = ConnectWise::InvoicePaymentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvoicePaymentsApi' do
    it 'should create an instact of InvoicePaymentsApi' do
      expect(@instance).to be_instance_of(ConnectWise::InvoicePaymentsApi)
    end
  end

  # unit tests for finance_invoices_id_payments_get
  # 
  # Get Payments
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @option opts [String] :order_by 
  # @option opts [String] :childconditions 
  # @option opts [String] :customfieldconditions 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @return [Array<Payment>]
  describe 'finance_invoices_id_payments_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finance_invoices_id_payments_payment_id_delete
  # 
  # Delete Payment By Id
  # @param id 
  # @param payment_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'finance_invoices_id_payments_payment_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finance_invoices_id_payments_payment_id_get
  # 
  # Get Payment By Id
  # @param id 
  # @param payment_id 
  # @param [Hash] opts the optional parameters
  # @return [Payment]
  describe 'finance_invoices_id_payments_payment_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finance_invoices_id_payments_payment_id_patch
  # 
  # Update Payment
  # @param id 
  # @param payment_id 
  # @param operations 
  # @param [Hash] opts the optional parameters
  # @return [Payment]
  describe 'finance_invoices_id_payments_payment_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finance_invoices_id_payments_payment_id_put
  # 
  # Replace Payment
  # @param id 
  # @param payment_id 
  # @param payment 
  # @param [Hash] opts the optional parameters
  # @return [Payment]
  describe 'finance_invoices_id_payments_payment_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for finance_invoices_id_payments_post
  # 
  # Create Payment
  # @param id 
  # @param payment 
  # @param [Hash] opts the optional parameters
  # @return [Payment]
  describe 'finance_invoices_id_payments_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
