
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::KPIsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'KPIsApi' do
  before do
    # run before each test
    @instance = ConnectWise::KPIsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KPIsApi' do
    it 'should create an instance of KPIsApi' do
      expect(@instance).to be_instance_of(ConnectWise::KPIsApi)
    end
  end

  # unit tests for system_kpis_count_get
  # 
  # Get K P I Count
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @return [Count]
  describe 'system_kpis_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_kpis_get
  # 
  # Get K P I
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @option opts [String] :order_by 
  # @option opts [String] :childconditions 
  # @option opts [String] :customfieldconditions 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @return [Array<KPI>]
  describe 'system_kpis_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for system_kpis_id_get
  # 
  # Get K P I By Id
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [KPI]
  describe 'system_kpis_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
