
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::ProjectPhasesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProjectPhasesApi' do
  before do
    # run before each test
    @instance = ConnectWise::ProjectPhasesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectPhasesApi' do
    it 'should create an instance of ProjectPhasesApi' do
      expect(@instance).to be_instance_of(ConnectWise::ProjectPhasesApi)
    end
  end

  # unit tests for project_projects_id_phases_count_get
  # 
  # Get Project Phases Count
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @return [Count]
  describe 'project_projects_id_phases_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_projects_id_phases_get
  # 
  # Get Project Phases
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @option opts [String] :order_by 
  # @option opts [String] :childconditions 
  # @option opts [String] :customfieldconditions 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @return [Array<ProjectPhase>]
  describe 'project_projects_id_phases_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_projects_id_phases_phase_id_delete
  # 
  # Delete Project Phase By Id
  # @param id 
  # @param phase_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'project_projects_id_phases_phase_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_projects_id_phases_phase_id_get
  # 
  # Get Project Phase By Id
  # @param id 
  # @param phase_id 
  # @param [Hash] opts the optional parameters
  # @return [ProjectPhase]
  describe 'project_projects_id_phases_phase_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_projects_id_phases_phase_id_patch
  # 
  # Update Project Phase
  # @param id 
  # @param phase_id 
  # @param operations 
  # @param [Hash] opts the optional parameters
  # @return [ProjectPhase]
  describe 'project_projects_id_phases_phase_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_projects_id_phases_phase_id_put
  # 
  # Replace Project Phase
  # @param id 
  # @param phase_id 
  # @param project_phase 
  # @param [Hash] opts the optional parameters
  # @return [ProjectPhase]
  describe 'project_projects_id_phases_phase_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_projects_id_phases_post
  # 
  # Create Project Phase
  # @param id 
  # @param project_phase 
  # @param [Hash] opts the optional parameters
  # @return [ProjectPhase]
  describe 'project_projects_id_phases_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
