=begin
#ConnectWise API

#ConnectWise API

OpenAPI spec version: 1.0.0
Contact: platform@connectwise.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::ProjectContactsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProjectContactsApi' do
  before do
    # run before each test
    @instance = ConnectWise::ProjectContactsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectContactsApi' do
    it 'should create an instact of ProjectContactsApi' do
      expect(@instance).to be_instance_of(ConnectWise::ProjectContactsApi)
    end
  end

  # unit tests for project_projects_id_contacts_contact_id_delete
  # 
  # Delete Project Contact By Id
  # @param id 
  # @param contact_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'project_projects_id_contacts_contact_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_projects_id_contacts_contact_id_get
  # 
  # Get Project Contact By Id
  # @param id 
  # @param contact_id 
  # @param [Hash] opts the optional parameters
  # @return [ProjectContact]
  describe 'project_projects_id_contacts_contact_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_projects_id_contacts_get
  # 
  # Get Project Contacts
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @option opts [String] :order_by 
  # @option opts [String] :childconditions 
  # @option opts [String] :customfieldconditions 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @return [Array<ProjectContact>]
  describe 'project_projects_id_contacts_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_projects_id_contacts_post
  # 
  # Create Project Contact
  # @param id 
  # @param contact 
  # @param [Hash] opts the optional parameters
  # @return [ProjectContact]
  describe 'project_projects_id_contacts_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
