
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::PurchaseOrderStatusEmailTemplatesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
RSpec.describe 'PurchaseOrderStatusEmailTemplatesApi' do
  before do
    # run before each test
    @instance = ConnectWise::PurchaseOrderStatusEmailTemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PurchaseOrderStatusEmailTemplatesApi' do
    it 'should create an instance of PurchaseOrderStatusEmailTemplatesApi' do
      expect(@instance).to be_instance_of(ConnectWise::PurchaseOrderStatusEmailTemplatesApi)
    end
  end

  # unit tests for procurement_purchaseorderstatuses_id_emailtemplates_count_get
  #
  # Get Purchase Order Status Email Templates Count
  # @param id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @return [Count]
  describe 'procurement_purchaseorderstatuses_id_emailtemplates_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_purchaseorderstatuses_id_emailtemplates_email_template_id_delete
  #
  # Delete Purchase Order Status Email Template By Id
  # @param id
  # @param email_template_id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'procurement_purchaseorderstatuses_id_emailtemplates_email_template_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_purchaseorderstatuses_id_emailtemplates_email_template_id_get
  #
  # Get Purchase Order Status Email Template By Id
  # @param id
  # @param email_template_id
  # @param [Hash] opts the optional parameters
  # @return [PurchaseOrderStatusEmailTemplate]
  describe 'procurement_purchaseorderstatuses_id_emailtemplates_email_template_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_purchaseorderstatuses_id_emailtemplates_email_template_id_patch
  #
  # Update Purchase Order Status Email Template
  # @param id
  # @param email_template_id
  # @param operations
  # @param [Hash] opts the optional parameters
  # @return [PurchaseOrderStatusEmailTemplate]
  describe 'procurement_purchaseorderstatuses_id_emailtemplates_email_template_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_purchaseorderstatuses_id_emailtemplates_email_template_id_put
  #
  # Replace Purchase Order Status Email Template
  # @param id
  # @param email_template_id
  # @param purchase_order_status_email_template
  # @param [Hash] opts the optional parameters
  # @return [PurchaseOrderStatusEmailTemplate]
  describe 'procurement_purchaseorderstatuses_id_emailtemplates_email_template_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_purchaseorderstatuses_id_emailtemplates_get
  #
  # Get Purchase Order Status Email Templates
  # @param id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :order_by
  # @option opts [String] :childconditions
  # @option opts [String] :customfieldconditions
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @return [Array<PurchaseOrderStatusEmailTemplate>]
  describe 'procurement_purchaseorderstatuses_id_emailtemplates_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_purchaseorderstatuses_id_emailtemplates_post
  #
  # Create Purchase Order Status Email Template
  # @param id
  # @param purchase_order_status_email_template
  # @param [Hash] opts the optional parameters
  # @return [PurchaseOrderStatusEmailTemplate]
  describe 'procurement_purchaseorderstatuses_id_emailtemplates_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
