
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::RMADispositionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RMADispositionsApi' do
  before do
    # run before each test
    @instance = ConnectWise::RMADispositionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RMADispositionsApi' do
    it 'should create an instance of RMADispositionsApi' do
      expect(@instance).to be_instance_of(ConnectWise::RMADispositionsApi)
    end
  end

  # unit tests for procurement_rma_dispositions_count_get
  # 
  # Get R M A Disposition Count
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @return [Count]
  describe 'procurement_rma_dispositions_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_rma_dispositions_get
  # 
  # Get R M A Disposition
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @option opts [String] :order_by 
  # @option opts [String] :childconditions 
  # @option opts [String] :customfieldconditions 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @return [Array<RMADisposition>]
  describe 'procurement_rma_dispositions_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_rma_dispositions_id_delete
  # 
  # Delete R M A Disposition By Id
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'procurement_rma_dispositions_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_rma_dispositions_id_get
  # 
  # Get R M A Disposition By Id
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [RMADisposition]
  describe 'procurement_rma_dispositions_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_rma_dispositions_id_patch
  # 
  # Update R M A Disposition
  # @param id 
  # @param operations 
  # @param [Hash] opts the optional parameters
  # @return [RMADisposition]
  describe 'procurement_rma_dispositions_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_rma_dispositions_id_put
  # 
  # Replace R M A Disposition
  # @param id 
  # @param rma_disposition 
  # @param [Hash] opts the optional parameters
  # @return [RMADisposition]
  describe 'procurement_rma_dispositions_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_rma_dispositions_post
  # 
  # Create R M A Disposition
  # @param rma_disposition 
  # @param [Hash] opts the optional parameters
  # @return [RMADisposition]
  describe 'procurement_rma_dispositions_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
