
require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::ShipmentMethodsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
RSpec.describe 'ShipmentMethodsApi' do
  before do
    # run before each test
    @instance = ConnectWise::ShipmentMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShipmentMethodsApi' do
    it 'should create an instance of ShipmentMethodsApi' do
      expect(@instance).to be_instance_of(ConnectWise::ShipmentMethodsApi)
    end
  end

  # unit tests for procurement_shipmentmethods_count_get
  #
  # Get Shipment Methods Count
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @return [Count]
  describe 'procurement_shipmentmethods_count_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_shipmentmethods_get
  #
  # Get Shipment Methods
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :order_by
  # @option opts [String] :childconditions
  # @option opts [String] :customfieldconditions
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @return [Array<ShipmentMethod>]
  describe 'procurement_shipmentmethods_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_shipmentmethods_id_delete
  #
  # Delete Shipment Method By Id
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'procurement_shipmentmethods_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_shipmentmethods_id_get
  #
  # Get Shipment Method By Id
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [ShipmentMethod]
  describe 'procurement_shipmentmethods_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_shipmentmethods_id_patch
  #
  # Update Shipment Method
  # @param id
  # @param operations
  # @param [Hash] opts the optional parameters
  # @return [ShipmentMethod]
  describe 'procurement_shipmentmethods_id_patch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_shipmentmethods_id_put
  #
  # Replace Shipment Method
  # @param id
  # @param shipment_method
  # @param [Hash] opts the optional parameters
  # @return [ShipmentMethod]
  describe 'procurement_shipmentmethods_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for procurement_shipmentmethods_post
  #
  # Create Shipment Method
  # @param shipment_method
  # @param [Hash] opts the optional parameters
  # @return [ShipmentMethod]
  describe 'procurement_shipmentmethods_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
