
require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ConnectWise::DepartmentMananager
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
RSpec.describe 'DepartmentMananager' do
  before do
    # run before each test
    @instance = ConnectWise::DepartmentMananager.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DepartmentMananager' do
    it 'should create an instance of DepartmentMananager' do
      expect(@instance).to be_instance_of(ConnectWise::DepartmentMananager)
    end
  end
  describe 'test attribute "count"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "re_assign_to_member"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
