
require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ConnectWise::MenuEntryLocation
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MenuEntryLocation' do
  before do
    # run before each test
    @instance = ConnectWise::MenuEntryLocation.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MenuEntryLocation' do
    it 'should create an instance of MenuEntryLocation' do
      expect(@instance).to be_instance_of(ConnectWise::MenuEntryLocation)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "location"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "menu_entry"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "_info"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

