
require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ConnectWise::RequestPasswordRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
RSpec.describe 'RequestPasswordRequest' do
  before do
    # run before each test
    @instance = ConnectWise::RequestPasswordRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RequestPasswordRequest' do
    it 'should create an instance of RequestPasswordRequest' do
      expect(@instance).to be_instance_of(ConnectWise::RequestPasswordRequest)
    end
  end
  describe 'test attribute "email"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
