
require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ConnectWise::ServiceEmailTemplateReference
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
RSpec.describe 'ServiceEmailTemplateReference' do
  before do
    # run before each test
    @instance = ConnectWise::ServiceEmailTemplateReference.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceEmailTemplateReference' do
    it 'should create an instance of ServiceEmailTemplateReference' do
      expect(@instance).to be_instance_of(ConnectWise::ServiceEmailTemplateReference)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "identifier"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "_info"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
