
require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ConnectWise::SkillReference
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SkillReference' do
  before do
    # run before each test
    @instance = ConnectWise::SkillReference.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SkillReference' do
    it 'should create an instance of SkillReference' do
      expect(@instance).to be_instance_of(ConnectWise::SkillReference)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "_info"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

