
require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ConnectWise::TimeAccrualDetail
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
RSpec.describe 'TimeAccrualDetail' do
  before do
    # run before each test
    @instance = ConnectWise::TimeAccrualDetail.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TimeAccrualDetail' do
    it 'should create an instance of TimeAccrualDetail' do
      expect(@instance).to be_instance_of(ConnectWise::TimeAccrualDetail)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "accrual_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Holiday", "PTO", "Sick", "Vacation"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.accrual_type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "start_year"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "end_year"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "hours"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "time_accrual"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "_info"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
