
require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ConnectWise::WorkflowActionAutomateParameter
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
RSpec.describe 'WorkflowActionAutomateParameter' do
  before do
    # run before each test
    @instance = ConnectWise::WorkflowActionAutomateParameter.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkflowActionAutomateParameter' do
    it 'should create an instance of WorkflowActionAutomateParameter' do
      expect(@instance).to be_instance_of(ConnectWise::WorkflowActionAutomateParameter)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
